language: python
services:
  - redis-server
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install coveralls"
# command to run tests
script: 
    nosetests --with-coverage --cover-erase --cover-package=pyla
after_success:
  coveralls
